// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMnYNudPbfnh7oPQEJJkOSObcfVfps9Gk',
    appId: '1:648012218010:web:d53f316217c30b0f58e923',
    messagingSenderId: '648012218010',
    projectId: 'contact-pro-97785',
    authDomain: 'contact-pro-97785.firebaseapp.com',
    storageBucket: 'contact-pro-97785.firebasestorage.app',
    measurementId: 'G-6YGCJX99L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZSJQOBgHO5pyTX6SQqC7hGSLfDc6Re5o',
    appId: '1:648012218010:android:177003635ed781c158e923',
    messagingSenderId: '648012218010',
    projectId: 'contact-pro-97785',
    storageBucket: 'contact-pro-97785.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_AUkfaU5xSKhgSZl4nGGHh45agSV2_AU',
    appId: '1:648012218010:ios:9c02f8de7be5534b58e923',
    messagingSenderId: '648012218010',
    projectId: 'contact-pro-97785',
    storageBucket: 'contact-pro-97785.firebasestorage.app',
    iosBundleId: 'com.example.contactPro',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_AUkfaU5xSKhgSZl4nGGHh45agSV2_AU',
    appId: '1:648012218010:ios:9c02f8de7be5534b58e923',
    messagingSenderId: '648012218010',
    projectId: 'contact-pro-97785',
    storageBucket: 'contact-pro-97785.firebasestorage.app',
    iosBundleId: 'com.example.contactPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMnYNudPbfnh7oPQEJJkOSObcfVfps9Gk',
    appId: '1:648012218010:web:2edf00464dcf8a5b58e923',
    messagingSenderId: '648012218010',
    projectId: 'contact-pro-97785',
    authDomain: 'contact-pro-97785.firebaseapp.com',
    storageBucket: 'contact-pro-97785.firebasestorage.app',
    measurementId: 'G-NS0Z4P77LC',
  );
}
